server:
  port: 8888

spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      global-cors:
        cors-configurations:
          '[/**]':
            allowed-origins:
             - "http://localhost:4200"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers:
              - "*"
            allow-credentials: true


#    gateway:
#        routes:
#          - id: r1
#            uri: http://localhost:8081
#            predicates:
#              - Path= /customers/**
#          - id: r2
#            uri: http://localhost:8082
#            predicates:
#              - Path= /products/**

